### PR TITLE
Implemente rib thickness and NACA finite TE

### PR DESCRIPTION
**Pull request by adrianinsaval**
Hi! me again, I've seen there is a Thickness property for ribs and its also in gui but it doesn't seem to have any effect so I added a couple lines that extrudes the rib face in the Y direction using this value when it is different than 0. Is it correct to asume the face will always be in the XZ plane? Is this the intended purpose of the Thickness property?

I've also implemented a property and checkbox in the gui that allow controling the finite_TE parameter from generateNACA, as well as some minor corrections and improvements in the gui.

### CODE REVIEW

**Comment by FredsFactory** [comment]
Hi thank a lot for your contribution. I use GitKraken to pull in my local folder your pull request, I hope I didn't make any mistakes😊.

The first test is not OK, the import of a DAT file doesn't work anymore
you have deleted the import "re" in line 28 file : airPlaneAirFoil.py
And the preview of DAT file is broken!
, here is the error message : 

_Traceback (most recent call last):
  File "/Users/fredericnivoix/Library/Preferences/FreeCAD/Mod/AirPlaneDesign/airPlaneDesingProfilUI.py", line 216, in updateTableViewDAT
    a,b=readpointsonfile(self.filePath)
  File "/Users/fredericnivoix/Library/Preferences/FreeCAD/Mod/AirPlaneDesign/airPlaneAirFoil.py", line 64, in readpointsonfile
    regex = re.compile(r'^\s*(?P<xval>(\-|\d*)\.\d+(E\-?\d+)?)\,?\s*(?P<yval>\-?\s*\d*\.\d+(E\-?\d+)?)\s*$')
NameError: name 're' is not defined_

**Comment by adrianinsaval** [comment]
yes that was solved in my other PR, I'll rebase on master an update this one, meanwhile if you want to test with the fix in your PC with gitkraken you can right click on the master branch and hit rebase, it shouln't give any conflicts.

**Comment by adrianinsaval** [comment]
thanks!

**Comment by FredsFactory** [comment]
You’re welcome

Fred

**Pull request merged**
